version: "2.2"

networks:
    db-admin-assignment-network:

volumes:
    mysqldata:
        driver: "local"

services:
    db-admin-assignment-app:
        container_name: db-admin-assignment-app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db-admin-assignment-mysql
        volumes:
            - .:/var/www/html/public
            - /var/www/html/public/vendor
            - /var/www/html/public/node_modules
        ports:
            - 8091:80
        environment:
            - WEB_DOCUMENT_ROOT=/var/www/html/public/public
        networks:
            - db-admin-assignment-network
        restart: on-failure

    db-admin-assignment-mysql:
        container_name: db-admin-assignment-mysql
        image: mysql:5.7
        volumes:
            - mysqldata:/var/lib/mysql
            - ./database/imports/:/docker-entrypoint-initdb.d
        ports:
            - 3311:3306
        environment:
            MYSQL_DATABASE: db_admin_assignment
            MYSQL_USER: db_admin_assignment
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - db-admin-assignment-network
        restart: on-failure